language: node_js
node_js: 
    - '11'
cache:
  directories:
    - node_modules    
install:
  - npm install
script:
  - npm run build
after_script:
  - cd ./dist
  - git init
  - git config user.name "AngelPP52"
  - git config user.email "1017118152@qq.com"
  - git add .
  - git commit -m "react project"
  - git push --force --quiet  "https://${GH_TOKEN}@github.com/AngelPP52/typescript_development.git" master:gh-pages